web/modules/contrib/opigno_learning_path/src/Form/DeleteAchievementsForm.php
<?php

namespace Drupal\opigno_learning_path\Form;

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\CloseModalDialogCommand;
use Drupal\Core\Database\Connection;
use Drupal\Core\Form\ConfirmFormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\group\Entity\Group;
use Drupal\opigno_module\Entity\UserModuleStatus;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Class LearningPathAdminSettingsForm.
 */
class DeleteAchievementsForm extends ConfirmFormBase {

  /**
   * Group.
   *
   * @var \Drupal\group\Entity\Group
   */
  protected $group;

  /**
   * Database connection.
   *
   * @var \Drupal\Core\Database\Connection
   */
  protected $database;

  /**
   * DeleteAchievementsForm constructor.
   */
  public function __construct(Connection $database) {
    $this->database = $database;
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    return new static($container->get('database'));
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'opigno_learning_path_delete_achievements';
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state, $group = NULL) {
    $form = parent::buildForm($form, $form_state);

    if (isset($group)) {
      $this->group = $group;
      $form['group'] = [
        '#type' => 'hidden',
        '#value' => $group->id(),
      ];
    }

    $form['actions']['submit']['#name'] = 'submit';

    $form['actions']['cancel']['#type'] = 'submit';
    $form['actions']['cancel']['#name'] = 'cancel';
    $form['actions']['cancel']['#value'] = $this->getCancelText();

    $is_ajax = $this->getRequest()->isXmlHttpRequest();
    if ($is_ajax) {
      $form['actions']['cancel']['#ajax'] = [
        'callback' => [$this, 'closeModal'],
        'event' => 'click',
      ];
    }

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function getQuestion() {
    return '';
  }

  /**
   * {@inheritdoc}
   */
  public function getDescription() {
    return $this->t('The contents of that training has changed. If you start again that training, your previous achievements for it will be deleted. Do you want to continue?');
  }

  /**
   * {@inheritdoc}
   */
  public function getCancelUrl() {
    if (isset($this->group)) {
      return $this->group->toUrl();
    }
    else {
      return Url::fromRoute('<front>');
    }
  }

  /**
   * {@inheritdoc}
   */
  public function getConfirmText() {
    return $this->t('Yes');
  }

  /**
   * {@inheritdoc}
   */
  public function getCancelText() {
    return $this->t('No');
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $element = $form_state->getTriggeringElement();
    if (isset($element['#name'])) {
      if ($element['#name'] === 'submit') {
        $uid = $this->currentUser()->id();
        $gid = $form_state->getValue('group');
        if (isset($gid)) {
          $this->database
            ->delete('opigno_learning_path_step_achievements')
            ->condition('uid', $uid)
            ->condition('gid', $gid)
            ->execute();

          $this->database
            ->delete('opigno_learning_path_achievements')
            ->condition('uid', $uid)
            ->condition('gid', $gid)
            ->execute();

          $group = Group::load($gid);
          if (isset($group)) {
            $modules = $group->getContentEntities('opigno_module_group');
            $module = reset($modules);
            if (!empty($module)) {
              // Create new unfinished user module attempt on the first module
              // of training to disable the training resume.
              $attempt = UserModuleStatus::create([]);
              $attempt->setModule($module);
              $attempt->setFinished(0);
              $attempt->save();
            }
          }

          $form_state->setRedirect('opigno_learning_path.steps.start', [
            'group' => $gid,
          ]);
        }
      }
      elseif ($element['#name'] === 'cancel') {
        $form_state->setRedirectUrl($this->getCancelUrl());
      }
    }
  }

  /**
   * Returns ajax response.
   */
  public function closeModal(array &$form, FormStateInterface $form_state) {
    $response = new AjaxResponse();
    $response->addCommand(new CloseModalDialogCommand());
    return $response;
  }

}

web/modules/contrib/opigno_learning_path/templates/group--learning-path--teaser-of-group.html.twig
{#
/**
 * @file
 * Default theme implementation to display a group.
 *
 * Available variables:
 * - group: The group entity with limited access to object properties and
 *   methods. Only "getter" methods (method names starting with "get", "has",
 *   or "is") and a few common methods such as "id" and "label" are available.
 *   Calling other methods (such as group.delete) will result in an exception.
 * - label: The title of the group.
 * - content: All group items. Use {{ content }} to print them all,
 *   or print a subset such as {{ content.field_example }}. Use
 *   {{ content|without('field_example') }} to temporarily suppress the
 *   printing of a given child element.
 * - url: Direct URL of the current group.
 * - attributes: HTML attributes for the containing element.
 *   The attributes.class element may contain one or more of the following
 *   classes:
 *   - group: The current template type (also known as a "theming hook").
 *   - group--[type]: The current group type. For example, if the group is a
 *     "Classroom" it would result in "group--classroom". Note that the machine
 *     name will often be in a short form of the human readable label.
 *   - group--[view_mode]: The View Mode of the group; for example, a
 *     teaser would result in: "group--teaser", and full: "group--full".
 * - title_attributes: Same as attributes, except applied to the main title
 *   tag that appears in the template.
 * - content_attributes: Same as attributes, except applied to the main
 *   content tag that appears in the template.
 * - title_prefix: Additional output populated by modules, intended to be
 *   displayed in front of the main title tag that appears in the template.
 * - title_suffix: Additional output populated by modules, intended to be
 *   displayed after the main title tag that appears in the template.
 * - view_mode: View mode; for example, "teaser" or "full".
 * - page: Flag for the full page state. Will be true if view_mode is 'full'.
 *
 * @see template_preprocess_group()
 *
 * @ingroup themeable
 */
#}
<div{{ attributes.addclass('group-opigno-course') }}>
  {{ title_prefix }}
  {% if not page %}
    <h3{{ title_attributes }}>
      <a href="{{ url }}" rel="bookmark">{{ label }}</a>
    </h3>
  {% endif %}
  {{ title_suffix }}
  <div class="row">
    <div id="group-content" {{ content_attributes.addClass('col-md-8') }}>
        <div class="bg-white px-3 py-3">
            {{ content.field_learning_path_description }}
        </div>
    </div>
  </div>
</div>

web/modules/contrib/opigno_learning_path/templates/group--learning-path.html.twig
{#
/**
 * @file
 * Default theme implementation to display a group.
 *
 * Available variables:
 * - group: The group entity with limited access to object properties and
 *   methods. Only "getter" methods (method names starting with "get", "has",
 *   or "is") and a few common methods such as "id" and "label" are available.
 *   Calling other methods (such as group.delete) will result in an exception.
 * - label: The title of the group.
 * - content: All group items. Use {{ content }} to print them all,
 *   or print a subset such as {{ content.field_example }}. Use
 *   {{ content|without('field_example') }} to temporarily suppress the
 *   printing of a given child element.
 * - url: Direct URL of the current group.
 * - attributes: HTML attributes for the containing element.
 *   The attributes.class element may contain one or more of the following
 *   classes:
 *   - group: The current template type (also known as a "theming hook").
 *   - group--[type]: The current group type. For example, if the group is a
 *     "Classroom" it would result in "group--classroom". Note that the machine
 *     name will often be in a short form of the human readable label.
 *   - group--[view_mode]: The View Mode of the group; for example, a
 *     teaser would result in: "group--teaser", and full: "group--full".
 * - title_attributes: Same as attributes, except applied to the main title
 *   tag that appears in the template.
 * - content_attributes: Same as attributes, except applied to the main
 *   content tag that appears in the template.
 * - title_prefix: Additional output populated by modules, intended to be
 *   displayed in front of the main title tag that appears in the template.
 * - title_suffix: Additional output populated by modules, intended to be
 *   displayed after the main title tag that appears in the template.
 * - view_mode: View mode; for example, "teaser" or "full".
 * - page: Flag for the full page state. Will be true if view_mode is 'full'.
 *
 * @see template_preprocess_group()
 *
 * @ingroup themeable
 */
#}

<div{{ attributes.addclass('group-opigno-course') }}>

  {{ title_prefix }}
  {% if not page %}
    <h2{{ title_attributes }}>
      <a href="{{ url }}" rel="bookmark">{{ label }}</a>
    </h2>
  {% endif %}
  {{ title_suffix }}
  <div class="row">
    {% if opigno_catalog_is_member(group.id()) %}
      {{ get_progress() }}
    {% endif %}
    <div class="col-md-4">
      <section>
        <h2 class="h4 bg-primary color-white text-uppercase mb-0 px-3 py-2">{{ 'Information'|t }}</h2>
        <div class="content bg-light py-2 pr-3">
          <div class="lp-image">
            {% if content.field_learning_path_media_image[0] %}
              {{ content.field_learning_path_media_image }}
            {% else %}
              {{ opigno_catalog_get_default_image('learning_path') }}
            {% endif %}
          </div>
          <div class="duration d-flex px-2 py-2 bg-white mt-2">
            <div class="label">{{ 'Length'|t }}</div>
            <div class="value text-right ml-auto">{{ group.field_learning_path_duration.value }}</div>
          </div>
          <div class="category d-flex px-2 py-2 bg-white mt-2">
            <div class="label">{{ 'Subject'|t }}</div>
            <div class="value text-right ml-auto">{{ learning_path_category }}</div>
          </div>
        </div>
        {{ get_join_group_link(null, null, {'class': ['opigno-quiz-app-course-button', 'bg-success', 'color-white', 'd-block', 'px-2', 'py-2', 'text-center', 'text-uppercase', 'join-link']}) }}
      </section>
    </div>
    <div id="group-content" {{ content_attributes.addClass('col-md-8') }}>
      <h2 class="h4 bg-primary text-uppercase color-white mb-0 px-3 py-2">{{ 'About this training'|t }}</h2>
      <div class="content bg-light px-2 pt-2">
        <div class="bg-white px-3 py-3">
          {{ content|without('field_learning_path_media_image', 'field_learning_path_duration', 'field_learning_path_category') }}
        </div>
      </div>
      {{ get_start_link(null, {'class': ['opigno-quiz-app-course-button', 'bg-success', 'color-white', 'd-block', 'px-2', 'py-2', 'text-center', 'text-uppercase']}) }}
    </div>
    {{ get_training_content() }}
  </div>
</div>

web/modules/contrib/opigno_learning_path/templates/multiselect-new-class.html.twig
{#
/**
 * @file
 * Default theme implementation for a multiselect element.
 *
 * Available variables:
 * - attributes: HTML attributes for the select tag.
 * - options: The option element children.
 *
 * @see template_preprocess_multiselect()
 *
 * @ingroup themeable
 */
#}
<div class="multiselect-wrapper">
  <div class="multiselect-available">
    <label for="{{ multiselect.available.id }}">{{ multiselect.available.label }}</label>
    <select{{ multiselect.available.attributes }}>
      {% for option in multiselect.available.options %}
        {% if option.type == 'optgroup' %}
          <optgroup label="{{ option.label }}">
            {% for sub_option in option.options %}
              <option value="{{ sub_option.value }}"{{ sub_option.selected ? ' selected="selected"' }}>{{ sub_option.label }}</option>
            {% endfor %}
          </optgroup>
        {% elseif option.type == 'option' %}
          <option value="{{ option.value }}"{{ option.selected ? ' selected="selected"' }}>{{ option.label }}</option>
        {% endif %}
      {% endfor %}
    </select>
  </div>
  <div class="multiselect-btns">
    <ul>
      <li class="multiselect-add">{{ multiselect.labels.add }}</li>
      <li class="multiselect-remove">{{ multiselect.labels.remove }}</li>
    </ul>
  </div>
  <div class="multiselect-selected">
    <label for="{{ multiselect.selected.id }}">{{ multiselect.selected.label }}</label>
    <select{{ multiselect.selected.attributes }}>
      {% for option in multiselect.selected.options %}
        {% if option.type == 'optgroup' %}
          <optgroup label="{{ option.label }}">
            {% for sub_option in option.options %}
              <option value="{{ sub_option.value }}"{{ sub_option.selected ? ' selected="selected"' }}>{{ sub_option.label }}</option>
            {% endfor %}
          </optgroup>
        {% elseif option.type == 'option' %}
          <option value="{{ option.value }}"{{ option.selected ? ' selected="selected"' }}>{{ option.label }}</option>
        {% endif %}
      {% endfor %}
    </select>
  </div>
</div>

web/modules/contrib/opigno_learning_path/templates/opigno-learning-path-courses.html.twig
<!-- group/{group}/inner-courses -->

<base href="{{ base_path ~ base_href }}">

<script type="text/javascript">
  window.appConfig = {
    formSubmitBtn: false,
    groupId: {{ learning_path_id }},
    groupType: '{{ group_type }}',
    apiBaseUrl: '{{ base_path }}',
    viewType: '{{ view_type }}',
    userHasInfoCard: '{{ user_has_info_card }}',
    hideInfocardUrl: '/opigno-group-manager/hide-info-card',
    getCourses: '/group/%groupId/courses/get-items',
    getEntitiesUrl: '/group/%groupId/get-items',
    getEntitiesPositionsUrl: '/group/%groupId/get-positions',
    setEntitiesPositionsUrl: '/group/%groupId/set-positions',
    getEntitiesTypesUrl: '/group/%groupId/get-item-types',
    getEntitiesAvailableUrl: '/group/%groupId/get-available-items',
    getEntityFormUrl: '/group/%groupId/item-form/%bundle/%entityId',
    getActivitiesUrl: '/group/%moduleId/get-activities',
    getGuidedNavigationUrl: '/group/%groupId/get-guided-navigation',
    getRequiredActivitiesUrl: '/group/%moduleId/get-activities-required',
    submitAddEntityFormUrl: '/group/%groupId/create-item/%bundle',
    addEntityUrl: '/group/%groupId/add-item',
    removeEntityUrl: '/group/%groupId/remove-item',
    addEntityLinkUrl: '/group/%groupId/add-link',
    updateEntityLinkUrl: '/group/%groupId/update-link',
    removeEntityLinkUrl: '/group/%groupId/remove-link',
    updateEntityMandatoryUrl: '/group/%groupId/update-mandatory',
    updateEntityMinScoreUrl: '/group/%groupId/update-min-score',
    updateEntitiesUrl: '/group/%groupId/update-entities',
    updateGuidedNavigationUrl: '/group/%groupId/update-guided-navigation',

    nextLink: '{{ next_link }}',
  };
</script>

<app-root class="d-block">Loading app...</app-root>

web/modules/contrib/opigno_learning_path/templates/opigno-learning-path-item-form.html.twig
{{ page.content|raw }}

web/modules/contrib/opigno_learning_path/templates/opigno-learning-path-modules.html.twig
<!-- group/{group}/inner-modules -->

<base href="{{ base_path ~ base_href }}">

<script type="text/javascript">
  window.appConfig = {
    formSubmitBtn: false,
    groupId: {{ learning_path_id }},
    apiBaseUrl: '{{ base_path }}',
    moduleContext: {{ module_context }},
    viewType: 'activities',
    userHasInfoCard: '{{ user_has_info_card }}',
    hideInfocardUrl: '/opigno-group-manager/hide-info-card',
    getEntitiesUrl: '/group/%groupId/get-items',
    getEntitiesPositionsUrl: '/group/%groupId/get-positions',
    getModulesUrl: '/group/%groupId/modules/get-items',
    getActivitiesUrl: '/group/%moduleId/get-activities',
    getExtPackageFormUrl: '/module/%opigno_module/add-external-package',
    getExtPackagePptFormUrl: '/module/%opigno_module/add-external-package/ppt',
    updateActivityUrl: '/group/%moduleId/update-activity',
    deleteActivityUrl: '/group/%moduleId/delete-activity',
    getActivityTypesUrl: '/module/manager/get-activity-types',
    getActivityFormUrl: '/module/%opigno_module/item-form/%type/%item',
    getActivityPreviewUrl: '/module/manager/activity-preview/%opigno_activity',
    getActivityListUrl: '/module/%opigno_module/manager/get-activities-list',
    addActivityUrl: '/module/%opigno_module/add-activity/%opigno_activity',
    addActivitiesBankUrl: '/opigno_module/%opigno_module/activities-bank-lpm',
    updateWeightUrl: '/module/manager/update-weight',
    nextLink: '{{ next_link }}',
  };
</script>

<app-root class="d-block">Loading app...</app-root>

web/modules/contrib/opigno_learning_path/templates/opigno-learning-path-training-content-step.html.twig
{#
/**
 * @file
 * Default theme implementation to display the training content step.
 *
 * Available variables:
 * - step: The step object with all the data.
 * - group: The Group object which the steps is part of.
 */
#}
<div class="lp_step">
  <div class="lp_step_title_wrapper">
    {% if step.mandatory %}
      <span class="lp_step_required"></span>
    {% endif %}
    <h3 class="lp_step_title">{{ step.name }}</h3>
  </div>
  {% if step.typology == 'Course' %}
    {% for course_step in step.course_steps %}
      <div class="lp_step_content">
        <div class="lp_step_summary">
          <div class="lp_step_summary_title_wrapper">
            <h3 class="lp_step_summary_title">{{ course_step.title }}</h3>
          </div>
          {{ course_step.summary_details_table }}
        </div>
      </div>
    {% endfor %}
  {% else %}
    <div class="lp_step_content">
      <div class="lp_step_summary">
        <div class="lp_step_summary_title_wrapper">
          <h3 class="lp_step_summary_title">{{ step.title }}</h3>
          <h4 class="lp_step_summary_subtitle">{{ step.sub_title }}</h4>
          {%  if step.description %}
            <div class="lp_step_summary_description">{{ step.description|raw }}</div>
          {% endif %}
        </div>
        {{ step.summary_details_table }}
      </div>
    </div>
  {% endif %}
</div>

web/modules/contrib/opigno_learning_path/templates/opigno-learning-path-training-content.html.twig
{#
/**
 * @file
 * Default theme implementation to display the training content.
 *
 * Available variables:
 * - content: All training content items. Use {{ content }} to print them all,
 *   or print a subset such as {{ content.tabs }}. Use
 *   {{ content|without('tabs') }} to temporarily suppress the
 *   printing of a given child element.
 */
#}
<div id="training-content-wrapper" class="col-12">
  {{ content }}
</div>

web/modules/contrib/opigno_learning_path/templates/page--group.html.twig
{#
/**
 * @file
 * Default theme implementation to display a single page.
 *
 * The doctype, html, head and body tags are not in this template. Instead they
 * can be found in the html.html.twig template in this directory.
 *
 * Available variables:
 *
 * General utility variables:
 * - base_path: The base URL path of the Drupal installation. Will usually be
 *   "/" unless you have installed Drupal in a sub-directory.
 * - is_front: A flag indicating if the current page is the front page.
 * - logged_in: A flag indicating if the user is registered and signed in.
 * - is_admin: A flag indicating if the user has permission to access
 *   administration pages.
 *
 * Site identity:
 * - front_page: The URL of the front page. Use this instead of base_path when
 *   linking to the front page. This includes the language domain or prefix.
 *
 * Page content (in order of occurrence in the default page.html.twig):
 * - messages: Status and error messages. Should be displayed prominently.
 * - node: Fully loaded node, if there is an automatically-loaded node
 *   associated with the page and the node ID is the second argument in the
 *   page's path (e.g. node/12345 and node/12345/revisions, but not
 *   comment/reply/12345).
 *
 * Regions:
 * - page.header: Items for the header region.
 * - page.primary_menu: Items for the primary menu region.
 * - page.secondary_menu: Items for the secondary menu region.
 * - page.highlighted: Items for the highlighted content region.
 * - page.help: Dynamic help text, mostly for admin pages.
 * - page.content: The main content of the current page.
 * - page.sidebar_first: Items for the first sidebar.
 * - page.sidebar_second: Items for the second sidebar.
 * - page.footer: Items for the footer region.
 * - page.breadcrumb: Items for the breadcrumb region.
 *
 * @see template_preprocess_page()
 * @see html.html.twig
 *
 * @ingroup themeable
 */
#}
<div class="layout-container">

  <header role="banner">
    {{ page.header }}
  </header>

  {{ page.primary_menu }}
  {{ page.secondary_menu }}

  {{ page.breadcrumb }}

  {{ page.highlighted }}

  {{ page.help }}

  <main role="main">
    <a id="main-content" tabindex="-1"></a>{# link is in html.html.twig #}

    <div class="layout-content">
      {{ page.content }}
    </div>{# /.layout-content #}

    {% if page.sidebar_first %}
      <aside class="layout-sidebar-first" role="complementary">
        {{ page.sidebar_first }}
      </aside>
    {% endif %}

    {% if page.sidebar_second %}
      <aside class="layout-sidebar-second" role="complementary">
        {{ page.sidebar_second }}
      </aside>
    {% endif %}

  </main>

  {% if page.footer %}
    <footer role="contentinfo">
      {{ page.footer }}
    </footer>
  {% endif %}

</div>{# /.layout-container #}

{{ join_group_form }}
{{ delete_lp_form }}

web/modules/contrib/opigno_learning_path/templates/region--content--admin--learning-path.html.twig
{#
/**
 * @file
 * Default theme implementation to display a region.
 *
 * Available variables:
 * - content: The content for this region, typically blocks.
 * - attributes: HTML attributes for the region <div>.
 * - region: The name of the region variable as defined in the theme's
 *   .info.yml file.
 *
 * @see template_preprocess_region()
 *
 * @ingroup themeable
 */
#}
{% if content %}
  <div>
    {{ step_list_top }}
    {{ attach_library('opigno_learning_path/creation_steps') }}
  </div>
  <div class="d-flex justify-content-end mb-4 text-uppercase">
    {{ next_link }}
  </div>
  <div class="row">
    <div class="col-md-3 aside-col">
      {{ step_list_aside }}
    </div>
    <div class="col-md-9 content-col">
      <div{{ attributes }}>
        {{ add_member_link }}
        {{ content }}
      </div>
    </div>
  </div>

{% endif %}